"""initial_schema

Revision ID: 0001
Revises: 
Create Date: 2024-05-20 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demande',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('date_etablissement', sa.DateTime(), nullable=True),
    sa.Column('approbation', sa.SmallInteger(), nullable=True),
    sa.Column('date_depart', sa.DateTime(), nullable=True),
    sa.Column('date_retour', sa.DateTime(), nullable=True),
    sa.Column('mode_transport', sa.String(length=30), nullable=True),
    sa.Column('lieu', sa.String(length=70), nullable=True),
    sa.Column('objet', sa.String(length=300), nullable=True),
    sa.Column('parcours', sa.String(length=150), nullable=True),
    sa.Column('agent', sa.String(length=70), nullable=True),
    sa.Column('agent_ident', sa.String(length=6), nullable=True),
    sa.Column('agent_structure', sa.String(length=9), nullable=True),
    sa.Column('agent_direction', sa.String(length=9), nullable=True),
    sa.Column('date_lecture', sa.DateTime(), nullable=True),
    sa.Column('date_action', sa.DateTime(), nullable=True),
    sa.Column('acteur_ident', sa.String(length=6), nullable=True),
    sa.Column('acteur', sa.String(length=70), nullable=True),
    sa.Column('acteur_poste', sa.String(length=50), nullable=True),
    sa.Column('acteur_poste_structure', sa.String(length=150), nullable=True),
    sa.Column('destinataire_ident', sa.String(length=6), nullable=True),
    sa.Column('destinataire', sa.String(length=70), nullable=True),
    sa.Column('destinataire_poste', sa.String(length=50), nullable=True),
    sa.Column('destinataire_poste_structure', sa.String(length=150), nullable=True),
    sa.Column('traitement', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_index(op.f('ix_demande_agent_structure'), 'demande', ['agent_structure'], unique=False)
    op.create_index(op.f('ix_demande_approbation'), 'demande', ['approbation'], unique=False)
    op.create_index(op.f('ix_demande_num'), 'demande', ['num'], unique=False)
    op.create_table('droit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('poste', sa.String(length=12), nullable=False),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.Column('designation', sa.String(length=80), nullable=False),
    sa.Column('structure', sa.String(length=9), nullable=False),
    sa.Column('libell_structure', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('libell_direction', sa.String(length=100), nullable=False),
    sa.Column('agent_ident', sa.String(length=6), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('poste_parent', sa.String(length=12), nullable=True),
    sa.Column('compte', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_droit_compte'), 'droit', ['compte'], unique=False)
    op.create_index(op.f('ix_droit_id'), 'droit', ['id'], unique=False)
    op.create_index(op.f('ix_droit_structure'), 'droit', ['structure'], unique=False)
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compte', sa.String(length=10), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('agent_ident', sa.String(length=6), nullable=False),
    sa.Column('agent', sa.String(length=70), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateur_compte'), 'utilisateur', ['compte'], unique=True)
    op.create_index(op.f('ix_utilisateur_id'), 'utilisateur', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisateur_id'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_compte'), table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_index(op.f('ix_droit_structure'), table_name='droit')
    op.drop_index(op.f('ix_droit_id'), table_name='droit')
    op.drop_index(op.f('ix_droit_compte'), table_name='droit')
    op.drop_table('droit')
    op.drop_index(op.f('ix_demande_num'), table_name='demande')
    op.drop_index(op.f('ix_demande_approbation'), table_name='demande')
    op.drop_index(op.f('ix_demande_agent_structure'), table_name='demande')
    op.drop_table('demande')
    # ### end Alembic commands ###
